update items set subject = 'Sachkunde Serie - h blau' where subject = 'Sachkunde Sevie - h.blau';
update items set subject = 'Sachkunde Serie - h blau' where subject = 'Sachkunde Sevie - h blau';

update items set classification = 'B - Biographie' where classification = 'B Biographie';
update items set classification = 'B - Biographie' where classification = 'Biographie';
update items set classification = 'Ba - Basteln / Handarbeit' where classification = 'Ba  Basteln';
update items set classification = 'Ba - Basteln / Handarbeit' where classification = 'Ba - Basteln - Handarbeit';
update items set classification = 'Ba - Basteln / Handarbeit' where classification = 'Ba - Basteln/ Handarbeit';
update items set classification = 'Ba - Basteln / Handarbeit' where classification = 'Basteln';
update items set classification = 'Ba - Basteln / Handarbeit' where classification = 'Basteln/Handarbeit';
update items set classification = 'Ba - Basteln / Handarbeit' where classification = 'Handarbeit';
update items set classification = 'Ba - Basteln / Handarbeit' where classification = 'Ba Basteln';
update items set classification = 'Be - Beschäftigung / Spielen' where classification = 'Be - Beschaeftigung';
update items set classification = 'Be - Beschäftigung / Spielen' where classification = 'Be - Beschaeftigung/ Spielen';
update items set classification = 'Be - Beschäftigung / Spielen' where classification = 'Be - Beschaeftigung/spielen';
update items set classification = 'Be - Beschäftigung / Spielen' where classification = 'Be -Beshaefitigung/Spielen';
update items set classification = 'Be - Beschäftigung / Spielen' where classification = 'Be Beschaeftigung';
update items set classification = 'Be - Beschäftigung / Spielen' where classification = 'Be Beschäftigung';
update items set classification = 'Be - Beschäftigung / Spielen' where classification = 'Beschäftigung';
update items set classification = 'Ber - Berufe' where classification = 'Ber Berufe';
update items set classification = 'Ber - Berufe' where classification = 'Berufe';
update items set classification = 'De - Deutsche Geschichte' where classification = 'De Deutsche Geschichte';
update items set classification = 'De - Deutsche Geschichte' where classification = 'De Deutsche Gschichte';
update items set classification = 'De - Deutsche Geschichte' where classification = 'De Deutschland';
update items set classification = 'Es - Essen / Kochen' where classification = 'Es Essen';
update items set classification = 'Es - Essen / Kochen' where classification = 'Es Essen/Kochen';
update items set classification = 'Es - Essen / Kochen' where classification = 'Kochen /essen';
update items set classification = 'G - Geschichte / Kulturen' where classification = 'G Geschichte Kulturen';
update items set classification = 'G - Geschichte / Kulturen' where classification = 'G Geschichte';
update items set classification = 'G - Geschichte / Kulturen' where classification = 'G Geschichte/Kulturen';
update items set classification = 'G - Geschichte / Kulturen' where classification = 'Geschichte Kulturen';
update items set classification = 'G - Geschichte / Kulturen' where classification = 'Geschichte';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geo - Geographie Atlanten';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geo Atlanten';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geo Gegrafie';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geo Geografie';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geo Geografie/Atlanten';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geo Geographie-Atlanten';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geo';
update items set classification = 'Geo - Geographie / Atlanten' where classification = 'Geografie';
update items set classification = 'Kl - Klassik' where classification = 'Goethe';
update items set classification = 'Kl - Klassik' where classification = 'KL Klassik';
update items set classification = 'Kl - Klassik' where classification = 'Klassik / Komponisten';
update items set classification = 'Kl - Klassik' where classification = 'Klassik';
update items set classification = 'Ku - Kunst / Architektur' where classification = 'Ku - Kunst';
update items set classification = 'Ku - Kunst / Architektur' where classification = 'Ku - Kunst/Architektur';
update items set classification = 'Ku - Kunst / Architektur' where classification = 'Kunst';
update items set classification = 'Ku - Kunst / Architektur' where classification = 'Ku Kunst';
update items set classification = 'Kö - Körper' where classification = 'Koe - Koerper';
update items set classification = 'Kö - Körper' where classification = 'Koe Koerper';
update items set classification = 'Kö - Körper' where classification = 'Koerper';
update items set classification = 'Le - Lernen / Lexikon' where classification = 'Le Lernen/Lexika';
update items set classification = 'Le - Lernen / Lexikon' where classification = 'Le Lernen/Lexikon';
update items set classification = 'Le - Lernen / Lexikon' where classification = 'Lernen/Lexika';
update items set classification = 'Le - Lernen / Lexikon' where classification = 'Lexika';
update items set classification = 'M - Musik / Liederbuch' where classification = 'Komponisten';
update items set classification = 'M - Musik / Liederbuch' where classification = 'M - Musik';
update items set classification = 'M - Musik / Liederbuch' where classification = 'M Musik';
update items set classification = 'M - Musik / Liederbuch' where classification = 'Music';
update items set classification = 'M - Musik / Liederbuch' where classification = 'Musik';
update items set classification = 'N - Natur / Umwelt / Jahreszeiten' where classification = 'N - Natur';
update items set classification = 'N - Natur / Umwelt / Jahreszeiten' where classification = 'N Natur';
update items set classification = 'N - Natur / Umwelt / Jahreszeiten' where classification = 'N Natur/Jahrzeit/Umwelt';
update items set classification = 'N - Natur / Umwelt / Jahreszeiten' where classification = 'Natur';
update items set classification = 'R - Religion' where classification = 'Religion';
update items set classification = 'Sp - Sport' where classification = 'Sp Sport';
update items set classification = 'Sp - Sport' where classification = 'Sport';
update items set classification = 'Te - Technik' where classification = 'Te Technik';
update items set classification = 'Te - Technik' where classification = 'Technik';
update items set classification = 'Ti - Tiere' where classification = 'Ti Tiere';
update items set classification = 'Ti - Tiere' where classification = 'Tiere';
update items set classification = 'Ve - Verkehr / Fahrzeuge' where classification = 'Ve - Fahrzeuge/Verkehr';
update items set classification = 'Ve - Verkehr / Fahrzeuge' where classification = 'Ve - Verkehr Fahrzeuge';
update items set classification = 'Ve - Verkehr / Fahrzeuge' where classification = 'Ve Verkehr';
update items set classification = 'Wir - Wirtschaft' where classification = 'Wir Wirtschaft';
update items set classification = 'Wo - Wohnen' where classification = 'Wo Wohnen';
